### PR TITLE
Enable/disable motion detection

### PR DESCRIPTION
**Pull request by nonsleepr**
Expose camera parameters as attributes as well.

Requires FuzzyMistborn/python-eufy-security#14 to be merged and published to PyPI as `python-eufy-security==0.1.2`.

### CODE REVIEW

**Comment by FuzzyMistborn** [comment]
This changes the setting per camera in the settings right?  Ie Settings-->Motion Detection-->Toggle off detection mode?  If so that's the main thing I've been looking for!

**Comment by nonsleepr** [comment]
Yes. It is per device. I have just a single device though, but the code targets specific `device_sn`.

**Comment by FuzzyMistborn** [comment]
Curious how you discovered the call/url to do this.  Maybe there's some other settings we can mimic/mirror.

**Comment by nonsleepr** [comment]
I decompiled the Android app and pulled the parameters mapping from there. I tried to poke into other settings with no success.
I changed the integration to expose all parameters in entity's state, so changing settings in the app and observing what changes in the state would be easy (need to implement forced update though).

**Comment by FuzzyMistborn** [comment]
Nice work!

**Comment by FuzzyMistborn** [comment]
Tested, so far so good!  Very quick response.
Few comments:
1) Probably shouldn't print the access token as an attribute in the states.  Should try to find a way to suppress.
2) May also want to generally limit what shows just because it's a long state attribute.  Things like the polygon may not need to be there.

**Comment by nonsleepr** [comment]
Yeah, I exposed it to see what's there. Probably only a couple of options should be actually shown. I guess the capacity could be a sensor, and maybe a snooze mode.

**Comment by FuzzyMistborn** [comment]
Yeah I'm going to open a new issue with some suggestions.

**Comment by nonsleepr** [comment]
BTW, `access_token` isn't the one from the API, it comes from HASS' mjpeg component.

**Pull request merged**
