### PR TITLE
Fix for HA 2020.12.0

### LINKED ISSUE #26: Error Eufy Camera on camera.py:46
Hi,
i have this error on homeassitant version:2020.12.0

Logger: homeassistant.components.camera
Source: custom_components/eufy_security/camera.py:46
Integration: Telecamera (documentation, issues)
First occurred: 00:38:42 (1 occurrences)
Last logged: 00:38:42
Error while setting up eufy_security platform for camera

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

Many thanks for all!

### PR DESCRIPTION
**Pull request by mikeskydev**
Fixes #26 

I was in the process of setting this up for the first time and was confused with the error, this quick change allowed me to register my doorbell as an entity.

There may be other issues since the 2020.12.0 update that this doesn't fix.

### CODE REVIEW

**Comment by redpider42** [comment]
See the solution by MizterB  : https://community.home-assistant.io/t/eufy-camera-integration/121758/382

**Comment by mikeskydev** [comment]
Yes, that's exactly the fix I've performed here, before that comment was written?

**Comment by golles** [comment]
Thanks for this PR, this fixes the issue for me.

**Comment by Jerommeke4** [comment]
indeed. nice fix. Was my solution as well!

**Review by golles — APPROVED** [review]
@nonsleepr please merge this

**Comment by ping-localhost** [comment]
Any chance you could tag master @nonsleepr? That way I can update using HACS.

**Pull request merged**
